#include <iostream>
#include <iomanip>
#include <string>
#include <stdlib.h>
#include <vector>
#include <map>
#include <chrono>
#include <random>
#include <bits/stdc++.h>
#include <fstream>
#include <sstream>
#include <stdio.h>
#include <time.h>
#pragma once

using std::string;
using std::cout;
using std::cin;
using std::endl;
using std::setw;
using std::left;
using std::right;
using std::vector;
using std::map;
using std::mt19937;